version: '3.1'
networks:
  laravel:
    driver: bridge

services:
    redis:
        image: 'redis:6.0.16-alpine'  # Updated version
        container_name: redis
        networks:
          - laravel

    postgres:
        image: 'postgres:14.11-alpine'  # Updated version
        container_name: postgres
        volumes:
          - './src:/var/www/html'
          - ./postgres-data:/var/lib/postgresql/data
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=lolipop1
          - POSTGRES_DB=subscribe_system
        ports:
          - '38004:5432'
        networks:
          - laravel

          
    # pgadmin:
    #     image: dpage/pgadmin4
    #     container_name: pgAdmin
    #     ports:
    #       - "5050:80"
    #     environment:
    #       PGADMIN_DEFAULT_EMAIL: nayem@g.com
    #       PGADMIN_DEFAULT_PASSWORD: nayem
    #     volumes:
    #       - ./pgadmin-data:/var/lib/pgadmin
    #     depends_on: 
    #       - postgres
    #     links:
    #       - postgres
    #     networks:
    #       - laravel

    webserver:
        image: 'nginx:alpine'
        container_name: nginx
        volumes:
            - './src:/var/www/html'
            - './dockerfiles/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '38000:80'
        depends_on:
          - php
          - redis
          - postgres
        networks:
          - laravel

    php:
        container_name: php
        user: www-data:www-data
        build: dockerfiles/php-fpm
        volumes:
            - './src:/var/www/html'
            - './dockerfiles/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
        networks:
          - laravel
